version: '3'

services:
  # Define el servicio de la base de datos
  db:
    image: mysql:8.0.32
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - cms-test
    volumes:
      - "db_app:/var/lib/mysql"

  # Define el servicio web
  nginx:
    build: 
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - cms-test
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    env_file:
      - .env.nginx

  
  php:
    build: 
      context: ./php
    networks:
      - cms-test
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor


volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:
  
networks:
    cms-test:
